# Generated by Django 5.2 on 2025-05-01 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="property",
            name="area",
            field=models.PositiveIntegerField(
                default=0, help_text="Area in square feet"
            ),
        ),
        migrations.AddField(
            model_name="property",
            name="bathrooms",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="property",
            name="bedrooms",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="property",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="property_images/"
            ),
        ),
    ]
